language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo apt-get update 

install: 
  # cmake make tool
  - sudo apt-get install -y cmake make libgtest-dev

  # protobuf 3.11.2
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protobuf-cpp-3.11.2.tar.gz
  - tar -xzvf protobuf-cpp-3.11.2.tar.gz
  - pushd protobuf-3.11.2 && ./configure && make -j2 && sudo make install && sudo ldconfig && popd

  # gtest lib
  - pushd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && popd

script: 
  - mkdir build
  - pushd build && cmake ../ -DBUILD_TEST=ON && make example xviz-test -j2 && popd
  - pwd && ./bin/xviz-test