language: cpp
compiler: gcc

dist: bionic

before_install:
  - sudo apt-get update 

install: 
  # cmake make tool
  - sudo apt-get install -y cmake make clang lcov tar wget

  # cmake
  - wget https://github.com/Kitware/CMake/releases/download/v3.17.4/cmake-3.17.4-Linux-x86_64.tar.gz
  - tar xvzf cmake-3.17.4-Linux-x86_64.tar.gz && pushd cmake-3.17.4-Linux-x86_64/cmake-3.17.4-Linux-x86_64/bin && cmake --version && popd

  # vcpkg
  - git clone https://github.com/microsoft/vcpkg.git
  - pushd vcpkg && pwd && ./bootstrap-vcpkg.sh && ./vcpkg install websocketpp nlohmann-json cpp-base64 protobuf gtest && popd

script: 
  # build with clang++
  - mkdir build
  - pushd build && ~/build/wx9698/xviz/cmake-3.17.4-Linux-x86_64/cmake-3.17.4-Linux-x86_64/bin/cmake ../ -DCMAKE_TOOLCHAIN_FILE=~/build/wx9698/xviz/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DBUILD_XVIZ_TESTS=ON && make example example-server xviz-test -j2 && popd
  - ./bin/xviz-test

  # build with g++ again
  - rm -rf build
  - mkdir build
  - pushd build && ~/build/wx9698/xviz/cmake-3.17.4-Linux-x86_64/cmake-3.17.4-Linux-x86_64/bin/cmake ../ -DCMAKE_TOOLCHAIN_FILE=~/build/wx9698/xviz/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_XVIZ_TESTS_LCOV=ON && make example example-server xviz-test -j2 && popd
  - ./bin/xviz-test
  - pushd build && make xviz-test-coverage -j2 && popd

after-success:

  # debug code coverage info
  - pwd
  - lcov --list ./build/xviz-test-coverage.info

  # submit code coverage info
  - bash <(curl -s https://codecov.io/bash) -f ./build/xviz-test-coverage.info || echo "Codecov did not collect coverage reports"
